name: DillFreedom
main: me.SupItsDillon.DillFreedom.DillFreedom
version: 1.5 beta
author: SupItsDillon
description: An add-on mainly targeted for all-op freedom servers.
 
commands:
  df-help:
    description: Help for the plugin
    usage: /<command>
  df-feed:
    description: Feeling hungry?
    usage: /<command> 
  df-heal:
    description: In the middle of PvP? About to die?
    usage: /<command>
  df-lol:
    description: One word. Lol.
    usage: /<command>
          
          
    