name: DillFreedom
version: 1.1
main: me.SupItsDillon.DillFreedom.DillFreedom
author: SupItsDillon
description: An add-on for the FreedomOP server.
commands:
    df-help:
        usage: /Command
        description: Help with the plugin
    df-feed:
        usage: /Command
        description: In the middle of a PVP match? Need to be fed?
    df-heal:
        usage: /Command
        description: Have the mobs been hurting you?
    df-lol:
        usage: /Command
        description: Lol.
